### ISSUE TITLE
Possible use of color-name API

### ISSUE THREAD

**Issue by meodai** [Andresuito/palette#1]
Awesome generator. I love how minimal it is.
I found it because you are consuming my color-name list.

Did you know that we have a public and free API?
https://github.com/meodai/color-name-api

Like that your users don't need to download the full list. The down side is that it takes a bit longer to return the names...

As a bonus there are other lists to choose from though.
PS you can test the other lists over here:

https://codepen.io/meodai/full/PoaRgLm

**Comment by Andresuito** [comment]
Thanks for the feedback!

I didn’t know about the API, so I really appreciate you mentioning it. I’ll test it and see how it affects performance. Thanks again for the tip.
